<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsAspireHost>true</IsAspireHost>
        <UserSecretsId>56b4118b-00a3-44f2-b0c8-f16c4b03b155</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.AppHost" Version="8.2.2" />
        <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="8.2.2" />
        <PackageReference Include="Aspire.Hosting.Redis" Version="8.2.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Api\Api.csproj" />
    </ItemGroup>

</Project>
