<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>0ebd6448-19be-49c7-a032-766e8e9b1c36</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Api.IntegrationTest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Azure.Storage.Blobs" Version="13.4.6" />
    <PackageReference Include="Aspire.StackExchange.Redis" Version="13.4.6" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="HotChocolate" Version="16.5.1" />
    <PackageReference Include="HotChocolate.AspNetCore" Version="16.5.1" />
    <PackageReference Include="HotChocolate.AspNetCore.Authorization" Version="16.5.1" />
    <PackageReference Include="HotChocolate.AspNetCore.CommandLine" Version="16.5.1" />
    <PackageReference Include="HotChocolate.Data" Version="16.5.1" />
    <PackageReference Include="HotChocolate.Data.EntityFramework" Version="16.5.1" />
    <PackageReference Include="HotChocolate.Types" Version="16.5.1" />
    <PackageReference Include="HotChocolate.Types.Analyzers" Version="16.5.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.StackExchangeRedis" Version="10.0.10" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.16" />
    <PackageReference Include="ScottBrady.IdentityModel" Version="4.1.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Seq" Version="9.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
    <ProjectReference Include="..\DbEf.Postgresql\DbEf.Postgresql.csproj" />
    <ProjectReference Include="..\DbEf\DbEf.csproj" />
    <ProjectReference Include="..\ServiceDefaults\ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\appsettings.Development.json">
      <Link>appsettings.Development.json</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\appsettings.json">
      <Link>appsettings.json</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Remove="Features\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Features\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="Features\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Features\**" />
  </ItemGroup>
</Project>
